version: '2'

services:
    rstudio:
        #depends_on:
        #  - rstudioInit
        build:
          context: ./rstudio.build
        volumes:
          - rstudioData:/home/rstudio/data:rw
        ports:
          - "8787:8787"

volumes:
    rstudioData:
        external: true

